use_frameworks!

platform :ios, '10.0'

target 'NSTVAwesomeValidator_Example' do
  pod 'NSTVAwesomeValidator', :path => '../'

  target 'NSTVAwesomeValidator_Tests' do
    inherit! :search_paths

    
  end
end
